from scr.processes_and_threading.camera_and_nn_process import CameraAndNNProcess
from scr.processes_and_threading.ui_process import UIProcess
from scr.processes_and_threading.parquet_process import ParquetProcess
