# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HMI_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import matplotlib.pyplot as plt
import numpy as np

from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class UIAction:
    pass


class UiMainWindow(object):
    def __init__(self):
        pass

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1147, 659)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 3, 2, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setIndent(-1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.lcd_Pos_UZK = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lcd_Pos_UZK.setFont(font)
        self.lcd_Pos_UZK.setDigitCount(8)
        self.lcd_Pos_UZK.setObjectName("lcd_Pos_UZK")
        self.gridLayout.addWidget(self.lcd_Pos_UZK, 5, 1, 1, 1)
        self.lcd_RollersSpeedSet = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lcd_RollersSpeedSet.setFont(font)
        self.lcd_RollersSpeedSet.setDigitCount(8)
        self.lcd_RollersSpeedSet.setObjectName("lcd_RollersSpeedSet")
        self.gridLayout.addWidget(self.lcd_RollersSpeedSet, 6, 1, 1, 1)
        self.l_Current_img = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_Current_img.sizePolicy().hasHeightForWidth())
        self.l_Current_img.setSizePolicy(sizePolicy)
        self.l_Current_img.setObjectName("l_Current_img")
        self.gridLayout.addWidget(self.l_Current_img, 4, 0, 1, 2)
        self.lcd_RollersSpeedAkt = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lcd_RollersSpeedAkt.setFont(font)
        self.lcd_RollersSpeedAkt.setSmallDecimalPoint(False)
        self.lcd_RollersSpeedAkt.setDigitCount(8)
        self.lcd_RollersSpeedAkt.setObjectName("lcd_RollersSpeedAkt")
        self.gridLayout.addWidget(self.lcd_RollersSpeedAkt, 7, 1, 1, 1)
        self.l_NG_img = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_NG_img.sizePolicy().hasHeightForWidth())
        self.l_NG_img.setSizePolicy(sizePolicy)
        self.l_NG_img.setObjectName("l_NG_img")
        self.gridLayout.addWidget(self.l_NG_img, 4, 2, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 2, 1, 1)
        self.btn_Transf = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Transf.sizePolicy().hasHeightForWidth())
        self.btn_Transf.setSizePolicy(sizePolicy)
        self.btn_Transf.setStyleSheet("QPushButton{\n"
                                      "    background-color: #c8c8c8;\n"
                                      "    font: 16pt \"MS Shell Dlg 2\";\n"
                                      "    border: 2px solid #f66867 ;\n"
                                      "    border-radius: 10;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: #a7a7a7;\n"
                                      "    }\n"
                                      "\n"
                                      "QPushButton:pressed{\n"
                                      "    background-color: #00ff00;\n"
                                      "    }")
        self.btn_Transf.setObjectName("btn_Transf")
        self.gridLayout.addWidget(self.btn_Transf, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 7, 2, 1, 1)
        self.l_Name_project = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_Name_project.sizePolicy().hasHeightForWidth())
        self.l_Name_project.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.l_Name_project.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.l_Name_project.setFont(font)
        self.l_Name_project.setAutoFillBackground(True)
        self.l_Name_project.setStyleSheet("")
        self.l_Name_project.setIndent(0)
        self.l_Name_project.setObjectName("l_Name_project")
        self.gridLayout.addWidget(self.l_Name_project, 0, 0, 1, 4)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 8, 2, 1, 1)
        self.lcd_Defect_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_Defect_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lcd_Defect_2.setFont(font)
        self.lcd_Defect_2.setDigitCount(8)
        self.lcd_Defect_2.setObjectName("lcd_Defect_2")
        self.gridLayout.addWidget(self.lcd_Defect_2, 5, 3, 1, 1)
        self.lcd_Temperature = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lcd_Temperature.setFont(font)
        self.lcd_Temperature.setDigitCount(8)
        self.lcd_Temperature.setObjectName("lcd_Temperature")
        self.gridLayout.addWidget(self.lcd_Temperature, 7, 3, 1, 1)
        self.lcd_Defect = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lcd_Defect.setFont(font)
        self.lcd_Defect.setDigitCount(8)
        self.lcd_Defect.setObjectName("lcd_Defect")
        self.gridLayout.addWidget(self.lcd_Defect, 6, 3, 1, 1)
        self.btn_Arch = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Arch.sizePolicy().hasHeightForWidth())
        self.btn_Arch.setSizePolicy(sizePolicy)
        self.btn_Arch.setStyleSheet("QPushButton{\n"
                                    "    background-color: #c8c8c8;\n"
                                    "    font: 16pt \"MS Shell Dlg 2\";\n"
                                    "    border: 2px solid #f66867 ;\n"
                                    "    border-radius: 10;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: #a7a7a7;\n"
                                    "    }\n"
                                    "\n"
                                    "QPushButton:pressed{\n"
                                    "    background-color: #00ff00;\n"
                                    "    }")
        self.btn_Arch.setObjectName("btn_Arch")
        self.gridLayout.addWidget(self.btn_Arch, 2, 3, 1, 1)
        self.lcdNumber_13 = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lcdNumber_13.setFont(font)
        self.lcdNumber_13.setDigitCount(8)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.gridLayout.addWidget(self.lcdNumber_13, 8, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 0, 1, 1)
        self.lcd_Diam = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lcd_Diam.setFont(font)
        self.lcd_Diam.setDigitCount(8)
        self.lcd_Diam.setObjectName("lcd_Diam")
        self.gridLayout.addWidget(self.lcd_Diam, 8, 1, 1, 1)
        self.btn_Parametr = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Parametr.sizePolicy().hasHeightForWidth())
        self.btn_Parametr.setSizePolicy(sizePolicy)
        self.btn_Parametr.setStyleSheet("QPushButton{\n"
                                        "    background-color: #c8c8c8;\n"
                                        "    font: 16pt \"MS Shell Dlg 2\";\n"
                                        "    border: 2px solid #f66867 ;\n"
                                        "    border-radius: 10;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: #a7a7a7;\n"
                                        "    }\n"
                                        "\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: #00ff00;\n"
                                        "    }")
        self.btn_Parametr.setObjectName("btn_Parametr")
        self.gridLayout.addWidget(self.btn_Parametr, 2, 1, 1, 1)
        self.btn_Main_screen = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Main_screen.sizePolicy().hasHeightForWidth())
        self.btn_Main_screen.setSizePolicy(sizePolicy)
        self.btn_Main_screen.setStyleSheet("QPushButton{\n"
                                           "    background-color: #c8c8c8;\n"
                                           "    font: 16pt \"MS Shell Dlg 2\";\n"
                                           "    border: 2px solid #f66867 ;\n"
                                           "    border-radius: 10;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover{\n"
                                           "    background-color: #a7a7a7;\n"
                                           "    }\n"
                                           "\n"
                                           "QPushButton:pressed{\n"
                                           "    background-color: #00ff00;\n"
                                           "    }")
        self.btn_Main_screen.setAutoDefault(False)
        self.btn_Main_screen.setObjectName("btn_Main_screen")
        self.gridLayout.addWidget(self.btn_Main_screen, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1147, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Текущий кадр"))
        self.label_14.setText(_translate("MainWindow", "Дефектный кадр"))
        self.label_4.setText(_translate("MainWindow", "Координата трубы ,мм"))
        self.label_5.setText(_translate("MainWindow", "Скорость валков заданная , мм/с"))
        self.l_Current_img.setText(_translate("MainWindow", "Здесь могла быть картинка"))
        self.l_NG_img.setText(_translate("MainWindow", "Дефектный кадр"))
        self.label_10.setText(_translate("MainWindow", "Скорость валков фактич. ,мм/с"))
        self.label_12.setText(_translate("MainWindow", "Обнаружен дефект"))
        self.label_15.setText(_translate("MainWindow", "Участок дефекта ,мм"))
        self.btn_Transf.setText(_translate("MainWindow", "Трансфокатор"))
        self.label_16.setText(_translate("MainWindow", "№ трубы на трубоотрезном станке"))
        self.l_Name_project.setText(_translate("MainWindow",
                                               "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Система термографии сварного шва электросварных труб</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "Пустое поле ,мм"))
        self.btn_Arch.setText(_translate("MainWindow", "Просмотр архивных записей"))
        self.label_11.setText(_translate("MainWindow", "Диаметр трубы ,мм"))
        self.btn_Parametr.setText(_translate("MainWindow", "Параметры системы"))
        self.btn_Main_screen.setText(_translate("MainWindow", "Главный экран"))

    @staticmethod
    def create_ui():
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = UiMainWindow()
        ui.setupUi(MainWindow)
        return ui, app, MainWindow

    def update_broke_img(self, img, interface, main_window, update):
        pix = self.get_pix_map(img)
        interface.l_NG_img.setPixmap(pix)
        if update:
            main_window.update()

    def update_current_img(self, img, interface, main_window, update):
        pix = self.get_pix_map(img)
        interface.l_Current_img.setPixmap(pix)
        if update:
            main_window.update()

    def get_pix_map(self, img):
        if len(img.shape) == 2:
            return self.get_pix_map_mono_ch(img)
        elif len(img.shape) == 3:
            return self.get_pix_map_rgb_ch(img)
        else:
            print('image wrong shape')

    @staticmethod
    def get_pix_map_mono_ch(img):
        image = QtGui.QImage(img, img.shape[1],
                             img.shape[0], img.shape[1], QtGui.QImage.Format.Format_Grayscale8)
        pix = QtGui.QPixmap(image)
        return pix

    @staticmethod
    def get_pix_map_rgb_ch(img):
        image = QtGui.QImage(img, img.shape[1],
                             img.shape[0], img.shape[1] * 3, QtGui.QImage.Format.Format_RGB888)
        pix = QtGui.QPixmap(image)
        return pix


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UiMainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
