from src.processes_and_threading.camera_and_nn_process import CameraAndNNProcess
from src.processes_and_threading.ui_process import UIProcess
from src.processes_and_threading.parquet_process import ParquetProcess
